const formulasMatematica = [
    "Fórmula da velocidade média: v = Δx/Δt",
    "Fórmula da aceleração média: a = Δv/Δt",
    "Fórmula de Bhaskara (equação quadrática): x = (-b ± √(b² - 4ac)) / (2a)",
    "Fórmula da área do triângulo: A = (base * altura) / 2",
    "Fórmula da área do retângulo: A = comprimento * largura",
    "Fórmula da área do quadrado: A = lado * lado",
    "Fórmula da área do trapézio: A = ((base maior + base menor) * altura) / 2",
    "Fórmula da área do círculo: A = π * raio²",
    "Fórmula da área da esfera: A = 4 * π * raio²",
    "Fórmula da área do cilindro: A = 2πr(r + h)",
    "Fórmula da área do cone: A = πr(r + g), onde g é a geratriz do cone",
    "Fórmula da área da pirâmide: A = (Perímetro da base * apótema) / 2",
    "Fórmula do perímetro do triângulo: P = lado1 + lado2 + lado3",
    "Fórmula do perímetro do retângulo: P = 2 * (comprimento + largura)",
    "Fórmula do perímetro do quadrado: P = 4 * lado",
    "Fórmula do perímetro do círculo: P = 2 * π * raio",
    "Fórmula do volume do cubo: V = lado³",
    "Fórmula do volume do paralelepípedo: V = comprimento * largura * altura",
    "Fórmula do volume do prisma: V = área da base * altura",
    "Fórmula do volume da esfera: V = (4/3) * π * raio³",
    "Fórmula do volume do cilindro: V = π * raio² * altura",
    "Fórmula do volume do cone: V = (1/3) * π * raio² * altura",
    "Fórmula da média aritmética: média = (soma dos valores) / (quantidade de valores)",
    "Fórmula da média ponderada: média ponderada = (valor1 * peso1 + valor2 * peso2 + ...) / (peso1 + peso2 + ...)",
    "Fórmula da média geométrica: média geométrica = √(valor1 * valor2 * ...)",
    "Fórmula da média harmônica: média harmônica = quantidade de valores / (1/valor1 + 1/valor2 + ...)",
    "Fórmula da progressão aritmética (termo geral): an = a1 + (n - 1) * r, onde an é o termo geral, a1 é o primeiro termo, n é a posição do termo e r é a razão",
    "Fórmula da soma dos termos de uma progressão aritmética: Sn = (n/2) * (a1 + an), onde Sn é a soma dos termos, n é a quantidade de termos, a1 é o primeiro termo e an é o último termo",
    "Fórmula da progressão geométrica (termo geral): an = a1 * r^(n - 1), onde an é o termo geral, a1 é o primeiro termo, n é a posição do termo e r é a razão",
    "Fórmula da soma dos termos de uma progressão geométrica: Sn = (a1 * (r^n - 1)) / (r - 1), onde Sn é a soma dos termos, a1 é o primeiro termo, n é a quantidade de termos e r é a razão",
    "Fórmula do teorema de Pitágoras: a² + b² = c², onde a, b e c são os lados de um triângulo retângulo",
    "Fórmula do teorema de Tales: a/b = c/d, onde a, b, c e d são segmentos proporcionais",
    "Fórmula da lei dos senos: a/sin(A) = b/sin(B) = c/sin(C), onde a, b e c são os lados de um triângulo e A, B e C são os ângulos opostos a esses lados, respectivamente",
    "Fórmula da lei dos cossenos: c² = a² + b² - 2ab*cos(C), onde a, b e c são os lados de um triângulo e C é o ângulo oposto ao lado c",
    "Fórmula da função linear: y = mx + b, onde m é o coeficiente angular e b é o coeficiente linear",
    "Fórmula da função quadrática: y = ax² + bx + c, onde a, b e c são coeficientes constantes",
    "Fórmula da função exponencial: y = a * b^x, onde a é a base, b é a base da exponencial e x é o expoente",
    "Fórmula da função logarítmica: y = log base b (x), onde b é a base do logaritmo e x é o número logaritmado",
    "Fórmula do binômio de Newton: (a + b)^n = C(n, 0) * a^n + C(n, 1) * a^(n-1) * b + C(n, 2) * a^(n-2) * b² + ... + C(n, n-1) * a * b^(n-1) + C(n, n) * b^n, onde C(n, k) é o coeficiente binomial",
    "Fórmula da soma dos termos de uma série aritmética: Sn = (n/2) * (a1 + an), onde Sn é a soma dos termos, n é a quantidade de termos, a1 é o primeiro termo e an é o último termo",
    "Fórmula da soma dos termos de uma série geométrica: Sn = (a1 * (r^n - 1)) / (r - 1), onde Sn é a soma dos termos, a1 é o primeiro termo, n é a quantidade de termos e r é a razão",
    "Fórmula da derivada de uma função constante: d/dx (k) = 0, onde k é uma constante",
    "Fórmula da derivada de uma função potência: d/dx (x^n) = n * x^(n-1), onde n é um expoente constante",
    "Fórmula da derivada de uma função exponencial: d/dx (a^x) = ln(a) * a^x, onde a é a base da exponencial e ln(a) é o logaritmo natural de a",
    "Fórmula da derivada da função logarítmica natural: d/dx (ln(x)) = 1/x",
    "Fórmula da derivada da função logarítmica na base a: d/dx (log base a (x)) = 1 / (x * ln(a)), onde ln(a) é o logaritmo natural de a",
    "Fórmula da derivada da função trigonométrica seno: d/dx (sin(x)) = cos(x)",
    "Fórmula da derivada da função trigonométrica cosseno: d/dx (cos(x)) = -sin(x)",
    "Fórmula da derivada da função trigonométrica tangente: d/dx (tan(x)) = sec²(x)",
    "Fórmula da derivada da função trigonométrica cotangente: d/dx (cot(x)) = -csc²(x)",
    "Fórmula da derivada da função trigonométrica secante: d/dx (sec(x)) = sec(x) * tan(x)",
    "Fórmula da derivada da função trigonométrica cossecante: d/dx (csc(x)) = -csc(x) * cot(x)",
    "Fórmula da regra do produto: d/dx (u * v) = u' * v + u * v', onde u e v são funções de x e u' e v' são as suas derivadas em relação a x",
    "Fórmula da regra do quociente: d/dx (u / v) = (u' * v - u * v') / v², onde u e v são funções de x e u' e v' são as suas derivadas em relação a x",
    "Fórmula da regra da cadeia: d/dx (f(g(x))) = f'(g(x)) * g'(x), onde f e g são funções de x e f' e g' são as suas derivadas em relação a x",
    "Fórmula da integral da função constante: ∫ k dx = kx + C, onde k é uma constante e C é a constante de integração",
    "Fórmula da integral da função potência: ∫ x^n dx = (x^(n+1)) / (n+1) + C, onde n é um expoente constante e C é a constante de integração",
    "Fórmula da integral da função exponencial: ∫ a^x dx = (a^x) / ln(a) + C, onde a é a base da exponencial, ln(a) é o logaritmo natural de a e C é a constante de integração",
    "Fórmula da integral da função logarítmica natural: ∫ ln(x) dx = x * (ln(x) - 1) + C",
    "Fórmula da integral da função logarítmica na base a: ∫ log base a (x) dx = (x * (ln(x) - ln(a))) / ln(a) + C, onde ln(a) é o logaritmo natural de a e C é a constante de integração",
    "Fórmula da integral da função trigonométrica seno: ∫ sin(x) dx = -cos(x) + C",
    "Fórmula da integral da função trigonométrica cosseno: ∫ cos(x) dx = sin(x) + C",
    "Fórmula da integral da função trigonométrica tangente: ∫ tan(x) dx = -ln(|cos(x)|) + C",
    "Fórmula da integral da função trigonométrica cotangente: ∫ cot(x) dx = ln(|sin(x)|) + C",
    "Fórmula da integral da função trigonométrica secante: ∫ sec(x) dx = ln(|sec(x) + tan(x)|) + C",
    "Fórmula da integral da função trigonométrica cossecante: ∫ csc(x) dx = ln(|csc(x) - cot(x)|) + C",
    "Fórmula da integral por substituição: ∫ f(g(x)) * g'(x) dx = ∫ f(u) du, onde u = g(x) e du = g'(x) dx",
    "Fórmula da integral por partes: ∫ u * v dx = u * v - ∫ v du, onde u e v são funções de x e du e dv são as suas derivadas em relação a x",
    "Fórmula da área do setor circular: A = (θ/360°) * π * r², onde θ é a medida do ângulo central e r é o raio do setor circular",
    "Fórmula do comprimento da circunferência: C = 2πr, onde r é o raio da circunferência",
    "Fórmula da área da elipse: A = π * a * b, onde a e b são os semi-eixos da elipse",
    "Fórmula da equação reduzida da reta: y = mx + n, onde m é o coeficiente angular e n é o coeficiente linear",
    "Fórmula da distância entre dois pontos: d = √((x2 - x1)² + (y2 - y1)²), onde (x1, y1) e (x2, y2) são as coordenadas dos dois pontos",
    "Fórmula do produto escalar de dois vetores: A · B = |A| * |B| * cos(θ), onde A e B são vetores, |A| e |B| são os seus módulos e θ é o ângulo entre eles",
    "Fórmula do produto vetorial de dois vetores: A x B = |A| * |B| * sin(θ) * n, onde A e B são vetores, |A| e |B| são os seus módulos, θ é o ângulo entre eles e n é o vetor normal ao plano formado por A e B",    
];

const formulasFisica = [
    "Fórmula da velocidade média: v = Δx/Δt",
    "Fórmula da aceleração média: a = Δv/Δt",
    // Mecânica:
    "Fórmula da velocidade média: v = Δx/Δt",
    "Fórmula da aceleração média: a = Δv/Δt",
    "Fórmula da velocidade final: v = v₀ + at",
    "Fórmula da posição final: x = x₀ + v₀t + (1/2)at²",
    "Fórmula da velocidade em queda livre: v = gt",
    "Fórmula da altura em queda livre: h = (1/2)gt²",
    "Fórmula do trabalho realizado: W = F * d * cosθ",
    "Fórmula da energia cinética: K = (1/2)mv²",
    "Fórmula da energia potencial gravitacional: U = mgh",
    "Fórmula da energia mecânica: E = K + U",
    "Fórmula da força centrípeta: Fc = (mv²)/r",
    "Fórmula da lei da gravitação universal: F = G * (m₁ * m₂)/r²",
    "Fórmula da lei de Hooke: F = k * Δx",
    "Fórmula do impulso: J = FΔt",
    "Fórmula do momento linear: p = mv",
    "Fórmula da lei da conservação do momento linear: m₁v₁ + m₂v₂ = m₁v₁' + m₂v₂'",
    "Fórmula da lei de conservação da energia mecânica: K₁ + U₁ = K₂ + U₂",
    "Fórmula do torque: τ = rFsinθ",
    "Fórmula do momento de inércia: I = m * r²",
    "Fórmula da lei de conservação do momento de inércia: I₁ω₁ = I₂ω₂",
    // Termodinâmica:
    "Fórmula da variação de temperatura (escala Celsius): ΔT = Tf - Ti",
    "Fórmula da variação de temperatura (escala Kelvin): ΔT = Tf - Ti",
    "Fórmula da quantidade de calor: Q = mcΔT",
    "Fórmula da capacidade térmica: C = Q/ΔT",
    "Fórmula da lei zero da termodinâmica: Tf = Tc",
    "Fórmula da lei de Boyle: P₁V₁ = P₂V₂",
    "Fórmula da lei de Charles: V₁/T₁ = V₂/T₂",
    "Fórmula da lei de Gay-Lussac: P₁/T₁ = P₂/T₂",
    "Fórmula da lei dos gases ideais: PV = nRT",
    "Fórmula da eficiência térmica: η = (W/Qh) * 100%",
    // Óptica:
    "Fórmula da velocidade da luz: c = λν",
    "Fórmula da frequência: ν = c/λ",
    "Fórmula do aumento linear: A = hi/ho",
    "Fórmula do aumento angular: A = θi/θo",
    "Fórmula da distância focal: f = (R₁ * R₂)/(R₁ + R₂)",
    "Fórmula da ampliação do espelho plano: A = -di/do",
    "Fórmula da ampliação do espelho esférico: A = hi/ho = -di/do",
    "Fórmula da lei de Snell: n₁sinθ₁ = n₂sinθ₂",
    "Fórmula da vergência da lente: P = 1/f",
    "Fórmula do aumento linear da lente: A = hi/ho = -di/do",
    // Eletromagnetismo:
    "Fórmula da força elétrica: F = k * (|q₁| * |q₂|)/r²",
    "Fórmula do campo elétrico: E = F/q",
    "Fórmula do potencial elétrico: V = k * |q|/r",
    "Fórmula do campo magnético: B = μ₀ * (I/2πr)",
    "Fórmula da força magnética em um condutor retilíneo: F = BILsinθ",
    "Fórmula da força magnética em uma carga em movimento: F = qvBsinθ",
    "Fórmula da força magnética em uma partícula carregada em um campo elétrico: F = qEsinθ",
    "Fórmula da força magnética em um condutor percorrido por corrente em um campo magnético: F = BILsinθ",
    "Fórmula da lei de Faraday: ε = -dΦ/dt",
    "Fórmula da lei de Ampère: B∫dl = μ₀ * Ienc",
    // Ondas e Som:
    "Fórmula da velocidade de uma onda: v = λf",
    "Fórmula da frequência de uma onda: f = v/λ",
    "Fórmula do período de uma onda: T = 1/f",
    "Fórmula da intensidade de uma onda: I = P/A",
    "Fórmula da lei de Snell-Descartes: n₁sinθ₁ = n₂sinθ₂",
    "Fórmula da frequência fundamental de uma corda vibrante: f₁ = v/2L",
    "Fórmula da frequência de harmônicos em uma corda vibrante: fn = nf₁",
    "Fórmula da velocidade do som: v = √(γRT)",
    "Fórmula da frequência fundamental de um tubo sonoro aberto: f₁ = v/2L",
    "Fórmula da frequência fundamental de um tubo sonoro fechado: f₁ = v/4L",
    // Eletrostática:
    "Fórmula da lei de Coulomb: F = k * (|q₁| * |q₂|)/r²",
    "Fórmula do campo elétrico: E = F/q",
    "Fórmula do potencial elétrico: V = k * |q|/r",
    "Fórmula da capacitância: C = Q/V",
    "Fórmula da energia potencial elétrica: U = (1/2)CV²",
    "Fórmula da energia elétrica armazenada em um capacitor: U = (1/2)QV",
    "Fórmula da energia potencial elétrica de um sistema de cargas: U = k * (|q₁||q₂|)/r",
    "Fórmula da lei de Gauss: Φ = E * A = Qenc/ε₀",
    "Fórmula da força elétrica entre placas paralelas de um capacitor: F = EQ",
    "Fórmula do campo elétrico produzido por um capacitor plano: E = σ/ε₀, onde σ é a densidade de carga superficial",
    // Magnetismo:
    "Fórmula da força magnética em um condutor retilíneo: F = BILsinθ",
    "Fórmula da força magnética em uma carga em movimento: F = qvBsinθ",
    "Fórmula da força magnética em uma partícula carregada em um campo elétrico: F = qEsinθ",
    "Fórmula da força magnética em um condutor percorrido por corrente em um campo magnético: F = BILsinθ",
    "Fórmula do campo magnético produzido por um fio retilíneo: B = (μ₀ * I)/(2πr)",
    "Fórmula do campo magnético no centro de uma espira circular: B = (μ₀ * I)/(2R)",
    "Fórmula do campo magnético no centro de uma solenoide: B = μ₀ * nI",
    "Fórmula da indução magnética em uma espira: Φ = BAcosθ",
    "Fórmula da força eletromotriz induzida: ε = -dΦ/dt",
    "Fórmula da lei de Ampère: B∫dl = μ₀ * Ienc",
    // Óptica Geométrica:
    "Fórmula da velocidade da luz: c = 3.00 x 10^8 m/s",
    "Fórmula da lei de Snell-Descartes: n₁sinθ₁ = n₂sinθ₂",
    "Fórmula da lente delgada: 1/f = (n-1) * (1/R₁ - 1/R₂)",
];

const formulasQuimica = [
    "Fórmula da massa molar: M = m/n",
    "Fórmula da concentração molar: C = n/V",
    "Fórmula da massa molar: M = m/n",
    "Fórmula da concentração molar: C = n/V",
    "Fórmula da lei de Avogadro: V = k * n",
    "Fórmula da lei dos gases ideais: PV = nRT",
    "Fórmula do número de mols: n = m/M",
    "Fórmula da reação de combustão: hidrocarboneto + O₂ → CO₂ + H₂O",
    "Fórmula da reação de síntese: A + B → AB",
    "Fórmula da reação de decomposição: AB → A + B",
    "Fórmula da reação de neutralização: ácido + base → sal + água",
    "Fórmula da reação de oxidação-redução: A + B → A⁺ + B⁻",
    "Fórmula do pH: pH = -log[H⁺]",
    "Fórmula da constante de equilíbrio: K = [C]^c [D]^d / [A]^a [B]^b",
    "Fórmula da velocidade média de uma reação: v = Δ[A]/Δt",
    "Fórmula da energia de ativação: Eₐ = R * T * ln(k/A)",
    "Fórmula da velocidade da reação: v = k[A]^a[B]^b",
    "Fórmula da constante de velocidade: k = Ae^(-Ea/RT)",
    "Fórmula do equilíbrio químico: aA + bB ⇌ cC + dD",
    "Fórmula da lei da velocidade de reação: r = k[A]^a[B]^b",
    "Fórmula da pressão parcial: P₁ = X₁ * P total",
    "Fórmula do produto de solubilidade: Ksp = [A]^a[B]^b",
    "Fórmula da solubilidade: S = n/V",
    "Fórmula da diluição: C₁V₁ = C₂V₂",
    "Fórmula da constante de ionização: Ka = [H₃O⁺][A⁻]/[HA]",
    "Fórmula do produto iônico da água: Kw = [H₃O⁺][OH⁻]",
    "Fórmula da constante de acidez: Ka = [H₃O⁺][A⁻]/[HA]",
    "Fórmula da constante de basicidade: Kb = [OH⁻][HB⁺]/[B]",
    "Fórmula do pH de uma solução ácida: pH = -log[H₃O⁺]",
    "Fórmula do pH de uma solução básica: pH = 14 - pOH",
    "Fórmula da lei de Lambert-Beer: A = εbc",
    "Fórmula do rendimento percentual: rendimento = (massa obtida experimentalmente / massa teórica) * 100%",
    "Fórmula da estequiometria: aA + bB → cC + dD",
    "Fórmula da lei de Raoult: P₁ = X₁",
];

// Exportar as fórmulas como um objeto
const formulas = {
    matematica: formulasMatematica,
    fisica: formulasFisica,
    quimica: formulasQuimica,
};

// Exportar o objeto para ser usado em outros arquivos
module.exports = formulas;